version: '3'
services:
  node:
    build:
      context: .
    image: alfaluck/qrl-node:latest
    container_name: qrl-node
    volumes:
      - "qrldata:/root/.qrl"
    ports:
      - "8080:8080"
      - "8888:8888"
      - "9000:9000"
    networks:
      - qrl_net
networks:
  qrl_net:
    driver: bridge
volumes:
  qrldata: